export const NAV = [
  { href: "/", label: "Overview" },
  {
    label: "Settings",
    children: [
      { href: "/settings/roles", label: "Roles" },
      { href: "/settings/access", label: "Access" },
      { href: "/settings/commands", label: "Commands" },
      { href: "/settings/command-visibility", label: "Command visibility" },
      { href: "/settings/channels", label: "Channels" },
      { href: "/settings/category", label: "Categories" },
      { href: "/settings/reputation", label: "Reputation" },
      { href: "/settings/ranks", label: "XP / Ranks" },
      { href: "/settings/welcome", label: "Welcome" },
      { href: "/settings/schedules", label: "Schedules" },
      { href: "/settings/certificates", label: "Certificates" },
      { href: "/settings/confessions", label: "Confessions" },
      { href: "/settings/modmail", label: "Modmail" },
      { href: "/settings/tasks", label: "Tasks" },
      { href: "/settings/misc", label: "Polls / Sticky / Helper" },
    ],
  },
  {
    label: "Moderation",
    children: [
      { href: "/moderation/warnings", label: "Warnings" },
      { href: "/moderation/notes", label: "Notes" },
      { href: "/moderation/logs", label: "Mod logs" },
      { href: "/moderation/ban-messages", label: "Ban messages" },
    ],
  },
  {
    label: "Operations",
    children: [
      { href: "/ops/certificates", label: "Certificates" },
      { href: "/ops/cert-assignees", label: "Cert assignees" },
      { href: "/ops/tasks", label: "Tasks" },
      { href: "/ops/stickies", label: "Stickies" },
      { href: "/ops/confessions", label: "Confessions" },
      { href: "/ops/reputation", label: "Reputation" },
      { href: "/ops/helpers", label: "Helper mappings" },
      { href: "/ops/qotd", label: "QOTD & SOTD" },
      { href: "/ops/xp", label: "XP" },
      { href: "/ops/xp-bans", label: "XP bans" },
      { href: "/ops/polls", label: "Polls" },
      { href: "/ops/exam-locking", label: "Exam locking" },
    ],
  },
] as const;
